networks:
  mg_net:
    external: true
    name: mg_net
secrets:
  mongo.root.password:
    external: true
    name: mongo.root.password
  mongoexpress.web.password:
    external: true
    name: mongoexpress.web.password
  pki.millegrilles.ssl.CAchain:
    external: true
    name: pki.millegrilles.ssl.CAchain.20190604
  pki.millegrilles.ssl.cert:
    external: true
    name: pki.millegrilles.ssl.cert.20190604
  pki.millegrilles.ssl.key:
    external: true
    name: pki.millegrilles.ssl.key.20190604
  pki.millegrilles.ssl.key_cert:
    external: true
    name: pki.millegrilles.ssl.key_cert.20190604
  pki.millegrilles.web.cert:
    external: true
    name: pki.millegrilles.web.cert.20190604
  pki.millegrilles.web.chain:
    external: true
    name: pki.millegrilles.web.chain.20190604
  pki.millegrilles.web.key:
    external: true
    name: pki.millegrilles.web.key.20190604
services:
  mq:
    deploy:
      placement:
        constraints:
        - node.labels.netzone.private == true
        - node.labels.millegrilles.mq == true
      replicas: 1
      resources:
        limits:
          cpus: '2.00'
          memory: 750M
      restart_policy:
        condition: any
        delay: 30s
    hostname: mq.pivoine.millegrilles.mdugre.info
    image: registry.maple.mdugre.info:5000/mg_rabbitmq:3.7-management_4
    networks:
      mg_net: null
    ports:
    - published: 5673
      target: 5673
    - published: 15671
      target: 443
    secrets:
    - source: pki.millegrilles.ssl.cert
    - source: pki.millegrilles.ssl.key
    - source: pki.millegrilles.ssl.CAchain
    - source: pki.millegrilles.web.cert
    - source: pki.millegrilles.web.key
    volumes:
    - mg-middleware-rabbitmq:/var/lib/rabbitmq:rw
version: '3.7'
volumes:
  mg-middleware-mongodata:
    name: mg-middleware-mongodata
  mg-middleware-nginx-conf:
    name: mg-middleware-nginx-conf
  mg-middleware-nginx-www:
    name: mg-middleware-nginx-www
  mg-middleware-rabbitmq:
    name: mg-middleware-rabbitmq

