networks:
  mg_net:
    external: true
    name: mg_net
secrets:
  mongo.root.password:
    external: true
    name: mongo.root.password
  mongoexpress.web.password:
    external: true
    name: mongoexpress.web.password
  ssl.millegrilles.cert:
    external: true
    name: ssl.pivoine.millegrilles.fullchain.20181226
  ssl.millegrilles.key:
    external: true
    name: ssl.pivoine.millegrilles.privkey.20181226
  ssl.millegrilles.key_cert:
    external: true
    name: ssl.pivoine.millegrilles.key_cert.20181226
services:
  mongo:
    command: --replSet rs0 --sslMode requireSSL --sslPEMKeyFile /run/secrets/ssl.millegrilles.key_cert
    deploy:
      placement:
        constraints:
        - node.labels.netzone.private == true
        - node.labels.millegrilles.database == true
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 1.0G
      restart_policy:
        condition: any
        delay: 30s
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo.root.password
      MONGO_INITDB_ROOT_USERNAME: root
    hostname: mongo.pivoine.millegrilles.mdugre.info
    image: registry.maple.mdugre.info:5000/mg_mongo.x86_64:v0.3.1
    networks:
      mg_net: null
    ports:
    - published: 27017
      target: 27017
    secrets:
    - source: mongo.root.password
    - source: ssl.millegrilles.key_cert
    volumes:
    - /mnt/mongodata1:/data/db:rw
  mq:
    deploy:
      placement:
        constraints:
        - node.labels.netzone.private == true
        - node.labels.millegrilles.mq == true
      replicas: 1
      resources:
        limits:
          cpus: '2.00'
          memory: 750M
      restart_policy:
        condition: any
        delay: 30s
    hostname: mq.pivoine.millegrilles.mdugre.info
    image: registry.maple.mdugre.info:5000/mg_rabbitmq.x86_64:v0.10.4.3
    networks:
      mg_net: null
    ports:
    - published: 5671
      target: 5671
    - published: 5673
      target: 5672
    - published: 15672
      target: 15672
    secrets:
    - source: ssl.millegrilles.cert
    - source: ssl.millegrilles.key
    volumes:
    - mg-consignation-rabbitmq:/var/lib/rabbitmq:rw
  nginx:
    deploy:
      placement:
        constraints:
        - node.labels.netzone.public == true
      replicas: 1
      resources:
        limits:
          cpus: '1.00'
          memory: 192M
      restart_policy:
        condition: any
        delay: 30s
    hostname: www.pivoine.millegrilles.mdugre.info
    image: registry.maple.mdugre.info:5000/mg_nginx.x86_64:v1.1-pivoine.1-pivoine
    networks:
      mg_net: null
    ports:
    - published: 31080
      target: 80
    - published: 31443
      target: 443
    secrets:
    - source: ssl.millegrilles.cert
    - source: ssl.millegrilles.key
    volumes:
    - /usr/share/nginx/pivoine/conf.d:/etc/nginx/conf.d:rw
    - /usr/share/nginx/pivoine/html:/usr/share/nginx/html:rw
  web-mongo-express:
    depends_on:
    - mongo
    deploy:
      placement:
        constraints:
        - node.labels.netzone.private == true
        - node.labels.millegrilles.consoles == true
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 75M
      restart_policy:
        condition: any
        delay: 30s
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongoexpress.web.password
      ME_CONFIG_BASICAUTH_USERNAME: mathieu
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_URL: '''mongodb://mongo:27017/admin?ssl=true'''
      ME_CONFIG_SITE_SSL_CRT_PATH: /run/secrets/ssl.millegrilles.cert
      ME_CONFIG_SITE_SSL_ENABLED: "true"
      ME_CONFIG_SITE_SSL_KEY_PATH: /run/secrets/ssl.millegrilles.key
      MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo.root.password
      VCAP_APP_HOST: '::'
      VCAP_APP_PORT: 443
    image: registry.maple.mdugre.info:5000/mg_md_mongo_express.x86_64:v0.4.1
    networks:
      mg_net: null
    ports:
    - published: 8081
      target: 443
    secrets:
    - source: mongo.root.password
    - source: mongoexpress.web.password
    - source: ssl.millegrilles.cert
    - source: ssl.millegrilles.key
version: '3.7'
volumes:
  mg-consignation-mongo:
    name: /mnt/mongodata1
  mg-consignation-nginx-etc:
    name: /usr/share/nginx/etc
  mg-consignation-nginx-www:
    name: /usr/share/nginx/html
  mg-consignation-rabbitmq:
    name: mg-consignation-rabbitmq

