# Stack pour consignation de MilleGrilles

# Use root/example as user/password credentials
version: '3.7'

services:

  # Base de donnees MongoDB
  mongo:
    image: mongo

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 500M
      restart_policy:
        condition: any
        delay: 30s

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    networks:
      - overlay

  # Systeme de messagerie RabbitMQ, incluant web manager
  rabbitmq:
    image: rabbitmq:3-management

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 250M
      restart_policy:
        condition: any
        delay: 30s

    ports:
      - "15672:15672"
      - "5671-5672:5671-5672"

    networks:
      - overlay

# Utilitaires pour gerer / debugger les services

  mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - overlay

networks:
  overlay:

