# Stack pour consignation de MilleGrilles

# Use root/example as user/password credentials
version: '3.7'

services:

  # Base de donnees MongoDB
  mongo:
    image: registry.maple.mdugre.info:5000/mg_mongo:1.2
    volumes:
      - mg-consignation-mongo:/data/db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1.5G
      restart_policy:
        condition: any
        delay: 30s

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    networks:
      - mg_net

  # Systeme de messagerie RabbitMQ, incluant web manager
  rabbitmq:
    image: registry.maple.mdugre.info:5000/mg_rabbitmq:1.2
    hostname: rabbitmq
    volumes:
      - mg-consignation-rabbitmq:/var/lib/rabbitmq
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 1G
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "15672:15672"
      - "5671-5672:5671-5672"
    networks:
      - mg_net

# Utilitaires pour gerer / debugger les services

  mongo-express:
    image: mongo-express
    depends_on:
        - mongo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 75M
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mg_net

volumes:
  mg-consignation-mongo:
    name: mg-consignation-mongo
  mg-consignation-rabbitmq:
    name: mg-consignation-rabbitmq

networks:
  mg_net:
    external: true
    name: mg_net


