# Stack pour consignation de MilleGrilles, middleware (logiciels serveurs)
version: '3.7'

services:

  # Base de donnees MongoDB
  mongo:
    image: registry.maple.mdugre.info:5000/mg_mongo.x86_64:v0.3.1
    command: --replSet rs0 --sslMode requireSSL --sslPEMKeyFile /run/secrets/ssl.pivoine.millegrilles.key_cert
    hostname: mongo.pivoine.millegrilles.mdugre.info
    volumes:
      - /mnt/mongodata1:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.private == true
          - node.labels.millegrilles.database == true
      resources:
        limits:
          cpus: "1.5"
          memory: 1.0G
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo.root.password
    networks:
      - mg_net
    secrets:
      - mongo.root.password
      - ssl.pivoine.millegrilles.key_cert

  # Systeme de messagerie RabbitMQ, incluant web manager
  mq:
    image: mg_rabbitmq.x86_64:v0.10.4.3
#    image: registry.maple.mdugre.info:5000/mg_rabbitmq.x86_64:v0.10.4
    hostname: mq.pivoine.millegrilles.mdugre.info
    volumes:
      - mg-consignation-rabbitmq:/var/lib/rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.private == true
          - node.labels.millegrilles.mq == true
      resources:
        limits:
          cpus: "2.00"
          memory: 750M
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "5671:5671"
      - "5673:5672"
#      - "15671:443"
      - "15672:15672"
    networks:
      - mg_net
    secrets:
      - ssl.pivoine.millegrilles.cert
      - ssl.pivoine.millegrilles.key

  # Proxy avec nginx
  nginx:
    image: registry.maple.mdugre.info:5000/mg_nginx.x86_64:v1.1-pivoine.1-pivoine
    hostname: www.pivoine.millegrilles.mdugre.info
    volumes:
      - /usr/share/nginx/pivoine/conf.d:/etc/nginx/conf.d
      - /usr/share/nginx/pivoine/html:/etc/nginx/html
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.public == true
      resources:
        limits:
          cpus: "1.00"
          memory: 192M
      restart_policy:
        condition: any
        delay: 30s
    ports:
     - "31080:80"
     - "31443:443"
    networks:
      - mg_net
    secrets:
      - ssl.pivoine.millegrilles.cert
      - ssl.pivoine.millegrilles.key

  # Utilitaires pour gerer / debugger les services
  web-mongo-express:
    image: registry.maple.mdugre.info:5000/mg_md_mongo_express.x86_64:v0.4.1
#    command: node app --url mongodb://mongo:27017/admin?ssl=true
    depends_on:
        - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.private == true
          - node.labels.millegrilles.consoles == true
      resources:
        limits:
          cpus: "0.5"
          memory: 75M
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - 8081:443
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mathieu
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
# Environnement production
      ME_CONFIG_MONGODB_URL: 'mongodb://mongo:27017/admin?ssl=true'
      MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo.root.password
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongoexpress.web.password
      VCAP_APP_HOST: '::'
      VCAP_APP_PORT: 443
      ME_CONFIG_SITE_SSL_ENABLED: 'true'
      ME_CONFIG_SITE_SSL_CRT_PATH: '/run/secrets/ssl.pivoine.millegrilles.cert'
      ME_CONFIG_SITE_SSL_KEY_PATH: '/run/secrets/ssl.pivoine.millegrilles.key'
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
# Environnement developpement
#      ME_CONFIG_MONGODB_URL: 'mongodb://192.168.1.110:27017/admin?ssl=true'
#      MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo.root.password
#      ME_CONFIG_BASICAUTH_PASSWORD: dev
    networks:
      - mg_net
    secrets:
      - mongo.root.password
      - mongoexpress.web.password
      - ssl.pivoine.millegrilles.cert
      - ssl.pivoine.millegrilles.key

volumes:
  mg-consignation-mongo:
    name: /mnt/mongodata1
  mg-consignation-rabbitmq:
    name: mg-consignation-rabbitmq
  mg-consignation-nginx-etc:
    name: /usr/share/nginx/etc
  mg-consignation-nginx-www:
    name: /usr/share/nginx/html

secrets:
  mongo.root.password:
    external: true
  mongoexpress.web.password:
    external: true
  ssl.pivoine.millegrilles.cert:
    external: true
    name: ssl.pivoine.millegrilles.fullchain.20181224
  ssl.pivoine.millegrilles.key:
    external: true
    name: ssl.pivoine.millegrilles.key.20181224
  ssl.pivoine.millegrilles.key_cert:
    external: true
    name: ssl.pivoine.millegrilles.key_cert.20181224

networks:
  mg_net:
    external: true
    name: mg_net
