# Stack pour stack web Coup D'Oeil de MilleGrilles
version: '3.7'

services:

  # Application Meteor pour Coup D'Oeil
  coupdoeilmeteor:
    image:  ${REGISTRY}/coupdoeil_meteor${MG_COUPDOEILMETEOR_IMAGE_VERSION}
    hostname: coupdoeilmeteor.${URL_DOMAIN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.private == true
          - node.labels.millegrilles.coupdoeil == true
      resources:
       limits:
          cpus: "1.00"
          memory: 512M
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "3001:3000"
    env_file:
      - services.env
    environment:
      MG_NOM_MILLEGRILLE: ${MG_NOM_MILLEGRILLE}
      MONGO_URL: mongodb://coupdoeilmeteor:higCYUD096aQUI67@mongo/mg-${MG_NOM_MILLEGRILLE}?ssl=true
      MONGO_OPLOG_URL: mongodb://coupdoeilmeteor:higCYUD096aQUI67@mongo/local?ssl=true&authSource=admin
      MG_MQ_USER: coupdoeil
      MG_MQ_PASSWORD: gLOUj3xLAj82
    networks:
      - mg_net
    secrets:
      - pki.millegrilles.ssl.key
      - pki.millegrilles.ssl.cert

  # Proxy avec nginx
  coupdoeilnginx:
    image: ${REGISTRY}/mg_nginx${MG_COUPDOEILNGINX_IMAGE_VERSION}
    hostname: coupdoeil.${URL_DOMAIN}
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - ${NGINX_WWW_PATH}:/etc/nginx/html
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.public == true
      resources:
        limits:
          cpus: "1.00"
          memory: 192M
      restart_policy:
        condition: any
        delay: 30s
    ports:
     - "30080:80"
     - "30443:443"
    environment:
      NGINX_CONFIG_FILE: meteor.conf     
    networks:
      - mg_net
    secrets:
      - pki.millegrilles.web.chain
      - pki.millegrilles.web.key

networks:
  mg_net:
    external: true
    name: mg_net

secrets:
  pki.millegrilles.web.chain:
    external: true
    name: ${PKI_MILLEGRILLES_WEB_PREFIX}.chain.${PKI_MILLEGRILLES_WEB_VERSION}
  pki.millegrilles.web.key:
    external: true
    name: ${PKI_MILLEGRILLES_WEB_PREFIX}.key.${PKI_MILLEGRILLES_WEB_VERSION}
  pki.millegrilles.ssl.key:
    external: true
    name: ${PKI_MILLEGRILLES_SSL_PREFIX}.key.${PKI_MILLEGRILLES_SSL_VERSION}
  pki.millegrilles.ssl.cert:
    external: true
    name: ${PKI_MILLEGRILLES_SSL_PREFIX}.cert.${PKI_MILLEGRILLES_SSL_VERSION}
