# Stack pour stack web Coup D'Oeil de MilleGrilles
version: '3.7'

services:

  # Application Meteor pour Coup D'Oeil
  coupdoeilreact:
    image:  ${REGISTRY}/coupdoeil_react${MG_COUPDOEILMETEOR_IMAGE_VERSION}
    hostname: coupdoeil.${URL_DOMAIN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.public == true
          - node.labels.millegrilles.coupdoeil == true
      resources:
       limits:
          cpus: "1.00"
          memory: 512M
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "8443:443"
    env_file:
      - services.env
    environment:
      MG_NOM_MILLEGRILLE: ${MG_NOM_MILLEGRILLE}
      MG_MQ_URL: ${MG_MQ_PREFIX}/${MG_NOM_MILLEGRILLE}
    networks:
      - mg_net
    secrets:
      - pki.millegrilles.ssl.key
      - pki.millegrilles.ssl.cert
      - pki.millegrilles.ssl.CAchain
      - pki.millegrilles.web.fullchain
      - pki.millegrilles.web.key

networks:
  mg_net:
    external: true
    name: mg_net

secrets:
  pki.millegrilles.web.fullchain:
    external: true
    name: ${PKI_MILLEGRILLES_WEB_PREFIX}.fullchain.${PKI_MILLEGRILLES_WEB_VERSION}
  pki.millegrilles.web.key:
    external: true
    name: ${PKI_MILLEGRILLES_WEB_PREFIX}.key.${PKI_MILLEGRILLES_WEB_VERSION}
  pki.millegrilles.ssl.key:
    external: true
    name: ${PKI_MILLEGRILLES_SSL_PREFIX}.key.${PKI_MILLEGRILLES_SSL_VERSION}
  pki.millegrilles.ssl.cert:
    external: true
    name: ${PKI_MILLEGRILLES_SSL_PREFIX}.cert.${PKI_MILLEGRILLES_SSL_VERSION}
  pki.millegrilles.ssl.CAchain:
    external: true
    name: ${PKI_MILLEGRILLES_SSL_PREFIX}.CAchain.${PKI_MILLEGRILLES_SSL_VERSION}
