networks:
  mg_net:
    external: true
    name: mg_net
secrets:
  pki.millegrilles.ssl.CAchain:
    external: true
    name: pki.millegrilles.ssl.CAchain.20190605
  pki.millegrilles.ssl.cert:
    external: true
    name: pki.millegrilles.ssl.cert.20190605
  pki.millegrilles.ssl.key:
    external: true
    name: pki.millegrilles.ssl.key.20190605
  pki.millegrilles.web.fullchain:
    external: true
    name: pki.millegrilles.web.fullchain.20190717_1
  pki.millegrilles.web.key:
    external: true
    name: pki.millegrilles.web.key.20190717_1
services:
  coupdoeilreact:
    deploy:
      placement:
        constraints:
        - node.labels.netzone.public == true
        - node.labels.millegrilles.coupdoeil == true
      replicas: 1
      resources:
        limits:
          cpus: '1.00'
          memory: 200M
      restart_policy:
        condition: any
        delay: 30s
    environment:
      CERT: /run/secrets/pki.millegrilles.web.fullchain
      MG_MQ_CAFILE: /run/secrets/pki.millegrilles.ssl.CAchain
      MG_MQ_CERTFILE: /run/secrets/pki.millegrilles.ssl.cert
      MG_MQ_KEYFILE: /run/secrets/pki.millegrilles.ssl.key
      MG_MQ_URL: amqps://mq:5673/pivoine
      MG_NOM_MILLEGRILLE: pivoine
      PRIVKEY: /run/secrets/pki.millegrilles.web.key
    hostname: coupdoeil.pivoine.millegrilles.mdugre.info
    image: registry.maple.mdugre.info:5000/coupdoeil_react:1.8.1
    networks:
      mg_net: null
    ports:
    - published: 8443
      target: 443
    secrets:
    - source: pki.millegrilles.ssl.key
    - source: pki.millegrilles.ssl.cert
    - source: pki.millegrilles.ssl.CAchain
    - source: pki.millegrilles.web.fullchain
    - source: pki.millegrilles.web.key
version: '3.7'

